//
//  PowerJackProgressionSeedScenario.swift
//  PowerJack
//
//  Week 1 fully logged with feedback; week 2 generated by the real progression planner.
//

import SwiftData

struct PowerJackProgressionSeedScenario {
    let container: ModelContainer
    let program: Program
    let weekOneWorkouts: [Workout]
    let weekTwoWorkouts: [Workout]
    /// Week 2's squat, held behind a manual check-in after severe pain in week 1.
    let checkInExercise: WorkoutExercise
}

extension PowerJackSeed {
    /// Logged performance for one week-1 exercise: (reps, weight in tenths of a pound) per set.
    private struct SeedLog {
        let sets: [(reps: Int, weightTenthsPounds: Int?)]
        let effort: LevelOfEffort
        let pain: LevelOfPain
    }

    static func weekTwoProgression() -> PowerJackProgressionSeedScenario {
        let container = makeInMemoryContainer()
        let context = container.mainContext
        let exercises = makeExercises()
        let templateProgram = makeTemplateProgram(exercises: exercises)

        for exercise in exercises {
            context.insert(exercise)
        }
        context.insert(templateProgram)

        let program = Program(programLengthWeeks: 4, templateProgram: templateProgram)
        context.insert(program)
        program.start()

        // Keyed by template position: [day][exercise].
        let logs: [[SeedLog]] = [
            [
                // Bench: all sets near the top of the range -> +5 lb.
                SeedLog(sets: [(12, 1350), (11, 1350)], effort: .challenge, pain: .none),
                // Squat: severe pain -> repeat and require a check-in.
                SeedLog(sets: [(8, 2250), (8, 2250)], effort: .veryHard, pain: .severe),
            ],
            [
                // Pull up (reps only): +1 rep.
                SeedLog(sets: [(8, nil), (7, nil)], effort: .challenge, pain: .mild),
                // Lat pulldown: one set under minimum -> hold it at the minimum.
                SeedLog(sets: [(10, 1200), (4, 1200)], effort: .veryHard, pain: .none),
            ],
            [
                // Lateral raise: moderate pain -> repeat.
                SeedLog(sets: [(12, 150), (12, 150)], effort: .easy, pain: .moderate),
                // Leg press: +1 rep.
                SeedLog(sets: [(10, 3150), (10, 3150)], effort: .challenge, pain: .none),
            ],
        ]

        let weekOneWorkouts = program.programWeeks[0].workouts
        for (workout, dayLogs) in zip(weekOneWorkouts, logs) {
            workout.startAndCascade()
            for (workoutExercise, log) in zip(workout.workoutExercises, dayLogs) {
                for warmup in workoutExercise.warmupSets {
                    warmup.complete()
                }
                for (workoutSet, entry) in zip(workoutExercise.workingSets, log.sets) {
                    workoutSet.reps = entry.reps
                    workoutSet.weightTenthsPounds = entry.weightTenthsPounds
                    workoutSet.complete()
                }
                workoutExercise.addFeedback(
                    feedback: ExerciseFeedback(levelOfEffort: log.effort, levelOfPain: log.pain)
                )
                workoutExercise.completeAndCascade()
            }
            program.finishWorkout(workout)
        }

        let weekTwoWorkouts = program.programWeeks[1].workouts
        let checkInExercise = weekTwoWorkouts[0].workoutExercises[1]

        do {
            try context.save()
        } catch {
            fatalError("Could not save seeded progression data: \(error)")
        }

        return PowerJackProgressionSeedScenario(
            container: container,
            program: program,
            weekOneWorkouts: weekOneWorkouts,
            weekTwoWorkouts: weekTwoWorkouts,
            checkInExercise: checkInExercise
        )
    }
}
